import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AuthProvider } from './context/AuthContext'; 
import "./globals.css";
import { FloatingDockDemo } from "./components/FloatingDock";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tebar Ilmu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider> {/* Bungkus aplikasi dengan AuthProvider */}
          {children}
          <div className="fixed bottom-4 left-0 right-0 flex justify-end md:justify-center z-10">
          <FloatingDockDemo/>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
